language: node_js
os:
  - linux
  - osx
env:
  - NODE=6
  - NODE=5
  - NODE=4
addons:
  apt:
    packages:
      - build-essential
      - clang
      - libdbus-glib-1-dev
      - libgtk2.0-dev
      - libnotify-dev
      - libgnome-keyring-dev
      - libgconf2-dev
      - libasound2-dev
      - libcap-dev
      - libcups2-dev
      - libxtst-dev
      - libxss1
      - libnss3-dev
      - gcc-multilib
      - g++-multilib
      - xvfb
install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE
  - nvm --version
  - node --version
  - npm --version
  - npm install
script:
  - npm test
notifications:
  email: false
